### ISSUE TITLE
Провести проверку на большом файле

### ISSUE THREAD

**Issue by alexkoss** [TyutterinYakov/UnrelatedGroups#1]
Файл: https://github.com/PeacockTeam/new-job/releases/download/v1.0/lng-big.7z

В ответе должно быть количество групп и время выполнения.

**Comment by TyutterinYakov** [comment]
Здравствуйте
Количество групп с количеством строк больше 1: 172481
Время выполнения(c): 10-15
![image](https://user-images.githubusercontent.com/45480231/220363933-9ab8d9f6-8ee6-4516-afc2-ef12a12ae701.png)
![image](https://user-images.githubusercontent.com/45480231/220364531-f1b680b5-b2fb-416f-b97e-4d0802714bc9.png)


Это в случае, если теперь мы считаем строки вида:
"88073.1";;"88073.1"
;"63887.1";"63887.1"
За корректные. То есть теперь пустой элемент представлен не как "", а пустым символом.

Если оставить старую логику, тогда 
![image](https://user-images.githubusercontent.com/45480231/220320224-063c2542-bd55-46cf-aed7-46121fc74870.png)
Так как ранее мы считали элементы строки вида: "43434.1" и пустые элементы, представленные пустым символом без кавычек как некорректные.

Если не совсем корректно, то уточните, пожалуйста, ТЗ, так как ранее были немного другие условия отсеивания строки

**Comment by alexkoss** [comment]
@TyutterinYakov Ответ некорректен. Кавычки можно убрать, они не несут нагрузки. Указанные строки считаются корректными.

**Comment by TyutterinYakov** [comment]
Количество групп с количеством строк больше 1: 105036
Ответ вроде бы верный, остается произвести оптимизацию алгоритма

**Comment by alexkoss** [comment]
А время выполнения?

**Comment by TyutterinYakov** [comment]
Я о нем сообщу позже, когда не будет стыдно) Сейчас это больше минуты. Я нашел причину некорректного ответа. Далее остается немного изменить подход к решению задачи

**Comment by alexkoss** [comment]
Понял. Тогда жду сообщения, когда можно будет по коду смотреть.

**Comment by TyutterinYakov** [comment]
![image](https://user-images.githubusercontent.com/45480231/220460541-15be52d0-2c7d-4e8f-89c6-68464fada424.png) Думаю, что можно смотреть) Прошу прощения, что долго, не сразу нашел время
